# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build, deploy then E2E test - CSEN Sport

permissions:
  contents: write

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 'Development'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Cache nextjs build
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.next
          key: build-${{ hashFiles('**/.env','**/*.lock','**/*.[jt]s*') }}

      - name: Install dependencies, build and vitest
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          XATA_API_KEY: ${{ secrets.XATA_API_KEY }}
        run: |
          npm install --legacy-peer-deps
          npm run build --if-present
          npm run test --if-present
          npm prune -f --omit-dev

      - name: Zip artifact for deployment
        run: zip -r release.zip ./.next ./node_modules ./public ./.env* ./next.config.js ./package.json ./package-lock.json ./CHANGELOG.md

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CCS-STUD0001'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7AA1FD78FB99429FBB5A58F87B3CA55C }}
          package: release.zip
          clean: true

  test:
    needs: deploy
    uses: bill-zhanxg/csen-sport/.github/workflows/reuse_playwright.yml@master
    secrets: inherit
    with:
      production: true
      shardIndex: '[1,2]'
      shardTotal: '[2]'
