name: Playwright Tests Development

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    uses: bill-zhanxg/csen-sport/.github/workflows/reuse_playwright.yml@master
    secrets: inherit
    with:
      production: false
      shardIndex: '[1,2,3,4,5,6]'
      shardTotal: '[6]'
