name: Playwright Tests Development

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    uses: bill-zhanxg/csen-sport/.github/workflows/reuse_playwright.yml@master
    secrets: inherit
    with:
      production: false
