name: Playwright Tests

on:
  workflow_call:
    inputs:
      production:
        required: true
        type: boolean

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: ${{ inputs.production && 'Production' || 'Development' }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Cache nextjs build
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.next
          key: build-${{ hashFiles('**/.env','**/*.lock','**/*.[jt]s*') }}

      - name: Cache playwright browsers
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/.cache
          key: playwright-browsers-${{ runner.os }}-${{ github.run_id }}
          restore-keys: playwright-browsers

      - name: Install dependencies, build and vitest
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          XATA_API_KEY: ${{ secrets.XATA_API_KEY }}
        run: |
          npm ci
          npm run build --if-present
          npm run test --if-present

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          XATA_API_KEY: ${{ secrets.XATA_API_KEY }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          BASE_URL: ${{ secrets.BASE_URL }}
          AUTH_MICROSOFT_ENTRA_ID_ID: ${{ secrets.AUTH_MICROSOFT_ENTRA_ID_ID }}
          AUTH_MICROSOFT_ENTRA_ID_SECRET: ${{ secrets.AUTH_MICROSOFT_ENTRA_ID_SECRET }}
          AUTH_MICROSOFT_ENTRA_ID_TENANT_ID: ${{ secrets.AUTH_MICROSOFT_ENTRA_ID_TENANT_ID }}
          TEST_LOGIN_ADMIN_PASSWORD: ${{ secrets.TEST_LOGIN_ADMIN_PASSWORD }}
          TEST_LOGIN_DEVELOPER_PASSWORD: ${{ secrets.TEST_LOGIN_DEVELOPER_PASSWORD }}
          TEST_LOGIN_TEACHER_PASSWORD: ${{ secrets.TEST_LOGIN_TEACHER_PASSWORD }}
          TEST_LOGIN_STUDENT_PASSWORD: ${{ secrets.TEST_LOGIN_STUDENT_PASSWORD }}
          TEST_LOGIN_BLOCKED_PASSWORD: ${{ secrets.TEST_LOGIN_BLOCKED_PASSWORD }}
        run: npm run playwright

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
