name: Install dependencies, build and vitest

on:
  workflow_call:
    inputs:
      rm-dev:
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies, build and vitest
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          npm ci
          npm run build --if-present
          npm run test --if-present
          if [ ${{ inputs.rm-dev }} == true ]; then
            npm prune --omit-dev
          fi
